# -*- coding: utf-8 -*-
"""DocuChat_Pro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E44UenEUHtJZxRIHjztFfXRtLo9sPx6D

Install Dependencies (Cell 1)
"""

# Cell 1: Install Required Libraries
# We use -qU to install 'quietly' (less text output) and 'upgrade' to the latest versions.
!pip install -qU langchain langchain-groq langchain-chroma pymupdf sentence-transformers

"""Initialize and Verify (Cell 2)"""

# Cell 2: Import libraries and test Groq API Connection
import os
import fitz  # This is PyMuPDF for document extraction
from langchain_groq import ChatGroq


# Initialize the Groq LLM
llm = ChatGroq(model_name="llama-3.3-70b-versatile", temperature=0)

# Test the connection
try:
    response = llm.invoke("Say 'API connection successful!' if you receive this message.")
    print("✅ Setup Complete:", response.content)
except Exception as e:
    print("❌ Error connecting to Groq:", e)

"""Get a Sample Document (Cell 3)"""

# Cell 3: Download a sample PDF for testing
# We are grabbing a public AI research paper from arXiv
!wget -q -O sample_paper.pdf https://arxiv.org/pdf/1706.03762.pdf

print("✅ Sample PDF 'sample_paper.pdf' downloaded successfully!")

"""Extract and Chunk the Text (Cell 4)"""

# Cell 4: Extract text and split into chunks
# We explicitly install the text splitter package first to fix the missing module error
!pip install -qU langchain-text-splitters

from langchain_text_splitters import RecursiveCharacterTextSplitter

# 1. Open the PDF and extract all the raw text
print("📖 Extracting text from PDF...")
doc = fitz.open("sample_paper.pdf")
full_text = ""

for page_num in range(len(doc)):
    page = doc.load_page(page_num)
    full_text += page.get_text()

print(f"✅ Extracted {len(full_text)} characters from the document.")

# 2. Chop the text into overlapping chunks
print("✂️ Chunking text...")
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,   # Maximum size of a chunk
    chunk_overlap=200  # Overlap to prevent cutting sentences in half
)

chunks = text_splitter.split_text(full_text)

print(f"✅ Split the document into {len(chunks)} chunks.")
print("-" * 50)
print("🔍 Preview of Chunk #1:\n")
print(chunks[0][:300] + "...\n")

"""Create and Run Cell 5"""

# Cell 5: Convert text chunks into Vector Embeddings and store in ChromaDB
# We explicitly install the langchain-huggingface integration package first
!pip install -qU langchain-huggingface

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

print("🚀 Initializing HuggingFace Embeddings model ('all-MiniLM-L6-v2')...")
# This downloads a lightweight, highly efficient open-source embedding model that runs completely free
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

print("📦 Creating local ChromaDB vector database from text chunks...")
# We take our text chunks, convert them to vectors via the embedding model, and save them in memory
vector_store = Chroma.from_texts(
    texts=chunks,
    embedding=embeddings
)

print("✅ Success! All 50 chunks have been vectorized and stored in ChromaDB.")

# Quick test search to prove it works
print("-" * 50)
query = "What is the main topic of this paper?"
print(f"🔍 Testing vector search with query: '{query}'")
matching_docs = vector_store.similarity_search(query, k=2)

print(f"📄 Found {len(matching_docs)} relevant text chunks.")
print("\nSnippet from top matching chunk:")
print(matching_docs[0].page_content[:250] + "...")

"""Query & Generation (Cell 6)"""

# Cell 6: Create the complete RAG Query Function and test it
def ask_docuchat(question: str):
    print(f"🔍 Question: {question}")

    # 1. Retrieve the top 3 most relevant text chunks from ChromaDB
    # 'k=3' tells the database to return the 3 closest matches
    retrieved_docs = vector_store.similarity_search(question, k=3)

    # 2. Combine the text contents of those 3 chunks into a single text block
    context_text = "\n\n---\n\n".join([doc.page_content for doc in retrieved_docs])

    # 3. Create a professional system prompt that forces the LLM to stay grounded
    system_prompt = f"""You are DocuChat Pro, an elite AI assistant.
Your task is to answer the user's question using ONLY the provided context below.
If the context does not contain the answer, say exactly: 'I cannot find the answer in the provided document.'
Do not make up facts or use outside knowledge.

CONTEXT FROM UPLOADED PDF:
{context_text}
"""

    # 4. package the prompt and send it to the Groq LLM
    from langchain_core.messages import SystemMessage, HumanMessage

    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=question)
    ]

    print("🧠 Sending query and context to Groq API...")
    response = llm.invoke(messages)

    print("\n🤖 DocuChat Pro Answer:")
    print("=" * 60)
    print(response.content)
    print("=" * 60)

# --- RUNNING THE TEST QUESTIONS ---
# Test 1: A factual question explicitly inside the document
ask_docuchat("What are the names of the authors of this paper?")

print("\n\n" + "#" * 80 + "\n\n")

# Test 2: Another document-specific question
ask_docuchat("What is the main advantage of the Transformer architecture mentioned?")

"""Production Script (Cell 7)"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# # Cell 7: Complete Production Code for DocuChat Pro
# import os
# import fitz  # PyMuPDF
# import streamlit as str_layout # We use this alias internally for layout management
# import streamlit as st
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain_huggingface import HuggingFaceEmbeddings
# from langchain_chroma import Chroma
# from langchain_groq import ChatGroq
# from langchain_core.messages import SystemMessage, HumanMessage
# 
# 
# # 2. Initialize core AI components once to save memory (Caching)
# @st.cache_resource
# def load_llm_and_embeddings():
#     llm = ChatGroq(model_name="llama-3.3-70b-versatile", temperature=0)
#     embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
#     return llm, embeddings
# 
# llm, embeddings = load_llm_and_embeddings()
# 
# # 3. Streamlit Web User Interface Styling
# st.set_page_config(page_title="DocuChat Pro", page_icon="📖", layout="wide")
# st.title("📖 DocuChat Pro: Multi-PDF RAG Chatbot")
# st.markdown("Upload any document and have a context-grounded conversation with it instantly.")
# 
# # 4. File Upload Section
# uploaded_file = st.file_uploader("Upload your PDF document", type=["pdf"])
# 
# if uploaded_file is not None:
#     st.success("📄 PDF uploaded successfully!")
# 
#     # Process file inside a spinner so the user knows the system is working
#     with st.spinner("Processing document... Extracting text & generating vector index..."):
#         # Read the uploaded PDF file bytes
#         file_bytes = uploaded_file.read()
#         doc = fitz.open(stream=file_bytes, filetype="pdf")
# 
#         # Extract raw text
#         full_text = ""
#         for page in doc:
#             full_text += page.get_text()
# 
#         # Segment text into overlapping chunks
#         text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
#         chunks = text_splitter.split_text(full_text)
# 
#         # Build local ephemeral ChromaDB instance
#         vector_store = Chroma.from_texts(texts=chunks, embedding=embeddings)
# 
#     st.info(f"System Status: Document tokenized into {len(chunks)} searchable chunks.")
# 
#     # 5. Conversational Interface Section
#     st.subheader("💬 Ask Your Document Anything")
#     user_question = st.text_input("Enter your question:")
# 
#     if user_question:
#         with st.spinner("Searching document data and synthesisng answer..."):
#             # Search database for top 4 relevant matches to avoid missing context
#             retrieved_docs = vector_store.similarity_search(user_question, k=4)
#             context_text = "\n\n---\n\n".join([d.page_content for d in retrieved_docs])
# 
#             # Construct rigorous grounded system template
#             system_prompt = f"""You are DocuChat Pro, an elite AI assistant.
# Your task is to answer the user's question using ONLY the provided context below.
# If the context does not contain the answer, say exactly: 'I cannot find the answer in the provided document.'
# Do not make up facts or use outside knowledge.
# 
# CONTEXT FROM UPLOADED PDF:
# {context_text}
# """
#             messages = [
#                 SystemMessage(content=system_prompt),
#                 HumanMessage(content=user_question)
#             ]
# 
#             # Execute inference
#             response = llm.invoke(messages)
# 
#             # Render output
#             st.markdown("### 🤖 DocuChat Pro Response:")
#             st.write(response.content)

"""Create the Requirements Manifest (Cell 8)"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# # Cell 8: Production dependencies configuration
# streamlit
# pymupdf
# langchain-text-splitters
# langchain-huggingface
# langchain-chroma
# langchain-groq
# sentence-transformers

"""Run the App and Create the Tunnel (Cell 9)"""

# Cell 9: Launch App with Tunnel-Friendly Network Settings
import urllib
import time

# 1. Ensure tools are installed
!pip install -qU streamlit
!npm install -g localtunnel > /dev/null 2>&1

# 2. Get the server IP address (LocalTunnel password)
server_ip = urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n")
print("🚨 CRITICAL: Copy this password. You will need it on the next screen!")
print(f"🔑 Password: {server_ip}")
print("-" * 50)

# 3. Start Streamlit with CORS disabled so the tunnel can load frontend files
print("🚀 Starting Streamlit Web Server (Bypassing CORS for Tunnel)...")
!streamlit run app.py --server.enableCORS=false --server.enableXsrfProtection=false & npx localtunnel --port 8501